### ISSUE TITLE
HAL_LL wrong generation in RTC

### ISSUE THREAD

**Issue by SergeiSOficial** [STMicroelectronics/STM32CubeL4#11]
STM32L412KBUx
IAR Arm 8.40.1

**Describe the bug**
HAL_LL project in RTC Alarm generated code is 
`RTC_AlarmStruct.AlarmMask = LL_RTC_ALMA_MASK_DATEWEEKDAY;`
Build Log:
`Error[Pe020]: identifier "RTC_ALARMMASK_DATEWEEKDAY" is undefined` 

**How To Reproduce**
1. all libs must be LL
2. Setup RTC with alarm

**Additional context**
Need to replace to 
`RTC_AlarmStruct.AlarmMask = LL_RTC_ALMA_MASK_DATEWEEKDAY;`

**Screenshots**
![image](https://user-images.githubusercontent.com/30231940/90892786-928d8780-e3c6-11ea-9103-672b6bbc2e05.png)

**Comment by ASELSTM** [comment]
Hi @SergeiSOficial,

First, allow me to thank you for your contribution. 

However, this issue is rather related to **CubeMX** than to the firmware published within this repository.
In fact, aspects related to CubeMX tool are not handled at GitHub level. They are rather treated at **ST Community** level, precisely within the CubeMX dedicated [section](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx). There, you may find posts that already raised the issue you are pointing out here. Otherwise, you can create a new post to submit your issue.

Since this issue is out of our scope, please allow me to close this issue. Thank you for your comprehension.

With regards,
