### ISSUE TITLE
B-L475E-IOT01A proximity code not working 

### ISSUE THREAD

**Issue by sundar19** [STMicroelectronics/STM32CubeL4#12]
**Describe the set-up**
 * B-L475E-IOT01A
 *STM32cube IDE

**Describe the bug**
The proximity example builds without any error ,after uploading the code into the board and opened  serial monitor and entered "n" to view the proximity value after which the code suddenly breaks and stops.

![Screenshot (56)](https://user-images.githubusercontent.com/31473503/91076659-6fc8d080-e65d-11ea-8c30-e269fafd590f.png)

I suspect some error in VL53L0X_PROXIMITY_GetDistance() , how to rectify this error
Thanks!!!

**Comment by RKOUSTM** [comment]
Hi @sundar19,

Welcome again to our GitHub organization. The problem seems to be related to migration to the CubeIDE. However, this public organization on GitHub is intended to promote co-development and issues posted here shall exclusively be related to the software published within the different repositories.
For any other issue (e.g. related to documentation, to hardware, to ecosystem, to user application, etc.), you shall address your questions to the [ST Community](https://community.st.com/s/topiccatalog). There you shall look for the adequate topic and submit your question or remark.

You can use the IDE proposed by ST (IAR, MDK-ARM and SW4STM32) for Proximity application on B-L475E-IOT01A all of them are working well.

Thank you for you contribution.

With regards,

**Comment by sundar19** [comment]
Thank you so much!
