### ISSUE TITLE
Hardfault of Proximity Project

### ISSUE THREAD

**Issue by TheSilentDawn** [STMicroelectronics/STM32CubeL4#47]
**Set-up**
- The board: B-L475E-IOT01A1
- IDE: STM32Cube IDE 1.6.1

I downloaded the SDK v1.17.0 from https://www.st.com/zh/embedded-software/stm32cubel4.html#get-software and imported the demo project Proximity into STM32Cube IDE.
When I started to run the program, it triggered the hardfault.
The hardfault call stack is below.

VL53L0X_calc_sigma_estimate api_core.c
VL53L0X_get_pal_range_status
VL53L0X_GetRangingMeasurementData
VL53L0X_PerformSingleRangingMeasurement
VL53L0X_PROXIMITY_GetDistance
Proximity_Test

Could you please help to double-check the demo project?
Thanks.

**Comment by RKOUSTM** [comment]
Hi @TheSilentDawn,

Thank you for your report. The problem seems to be related to migration to the CubeIDE. However, this public organization on GitHub is intended to promote co-development and issues posted here shall exclusively be related to the software published within the different repositories.
For any other issue (e.g. related to documentation, to hardware, to ecosystem, to user application, etc.), you shall address your questions to the [ST Community](https://community.st.com/s/topic/0TO0X000000BSqSWAW/stm32-mcus). There you shall look for the adequate topic and submit your question or remark.

You can use the IDE proposed by ST (IAR, MDK-ARM and SW4STM32) for Proximity application on B-L475E-IOT01A all of them are working well.

Thank you for you contribution.

With regards,
